# Generated by Django 4.2.1 on 2023-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_crated',
            new_name='data_created',
        ),
    ]
